---
service: bow
frameworkVersion: '2'
disabledDeprecations:
  - CLI_OPTIONS_SCHEMA

plugins:
  - serverless-deployment-bucket
  - serverless-prune-plugin
  - serverless-python-requirements
  - serverless-dynamodb-local
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-add-api-key

package:
  patterns:
    - '!*/**'
    - '!*.*'
    - 'app/**'
    - '!app/**/__pycache__/**'
    - '!app/**/.DS_Store'

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'ap-northeast-1'}
  deploymentBucket:
    name: ${self:custom.resourcePrefix}-sls-deploy
    serverSideEncryption: AES256
  lambdaHashingVersion: 20201221
  logRetentionInDays: 30
  endpointType: edge
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            Fn::Join:
              - ":"
              - - arn:aws:dynamodb
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - table/${self:custom.resourcePrefix}-*
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:
            - !Sub "${ImageBucket.Arn}"
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - !Sub "${ImageBucket.Arn}/*"

custom:
  resourcePrefix: ${self:service}-${self:provider.stage}
  prune:
    automatic: true
    number: 3
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: true
  apigwBinary:
    types:
      - multipart/form-data
  dynamodb:
    stages:
      - local
    start:
      dbPath: ./.dynamodb-data/
      migrate: false
      seed: false
    seed: ${file(./tests/data/testdata.yml)}
  domainName:
    local: bow-api-dev.jozuo.work
    dev: bow-api-dev.jozuo.work
    stg: bow-api-stg.jozuo.work
    prod: bow-api.jozuo.work
  customDomain:
    domainName: ${self:custom.domainName.${self:provider.stage}}
    basePath: ""
    certificateName: "*.jozuo.work"
    certificateArn: arn:aws:acm:ap-northeast-1:602526353155:certificate/f59fa794-8ee6-4ec3-94e6-d16c1a3a9a22
    createRoute53Record: false
    endpointType: regional
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false
  apiKeys:
    - name: bow-api

functions:
  api:
    handler: app.api.main.handler
    name: ${self:custom.resourcePrefix}-api
    environment:
      TABLE_PREFIX: ${self:custom.resourcePrefix}
      IMAGE_BUCKET: ${self:custom.resourcePrefix}-image
    events:
      - http:
          path: /{path+}
          method: any
          private: true
          cors: true

resources:
  - ${file(./resource/s3.yml)}
  - ${file(./resource/dynamodb.yml)}
  - ${file(./resource/api-gateway.yml)}
