Resources:
  OwnerTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:custom.resourcePrefix}-owner
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  DogTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:custom.resourcePrefix}-dog
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: owner_id
          AttributeType: S
        - AttributeName: dog_id
          AttributeType: S
      KeySchema:
        - AttributeName: owner_id
          KeyType: HASH
        - AttributeName: dog_id
          KeyType: RANGE
  TaskTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:custom.resourcePrefix}-task
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: owner_id
          AttributeType: S
        - AttributeName: task_id
          AttributeType: S
      KeySchema:
        - AttributeName: owner_id
          KeyType: HASH
        - AttributeName: task_id
          KeyType: RANGE
  EventTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:custom.resourcePrefix}-event
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: owner_id
          AttributeType: S
        - AttributeName: event_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: owner_id
          KeyType: HASH
        - AttributeName: event_id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: event-lsi1
          KeySchema:
            - AttributeName: owner_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
              ProjectionType: ALL

